### ISSUE TITLE
Examples use role="section" as opposed to "region"

### ISSUE THREAD

**Issue by Malvoz** [aleventhal/aria-annotations#2]
[This example](https://github.com/aleventhal/aria-annotations#example----comments-for-entire-article) is using [`role="section"`](https://www.w3.org/TR/wai-aria-1.1/#section):

> <var>section</var> is an abstract role used for the ontology. Authors should not use this role in content.

I presume the intention was to use [`region`](https://www.w3.org/TR/wai-aria-1.1/#region)?

**Comment by aleventhal** [comment]
Thanks, fixed.
